// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Upper_inv_HH_
#define _Upper_inv_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "inverse_top_fadd_hbi.h"
#include "inverse_top_fmul_cud.h"
#include "inverse_top_fdiv_dEe.h"

namespace ap_rtl {

struct Upper_inv : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > U_address0;
    sc_out< sc_logic > U_ce0;
    sc_in< sc_lv<32> > U_q0;
    sc_out< sc_lv<4> > U_inv_address0;
    sc_out< sc_logic > U_inv_ce0;
    sc_out< sc_logic > U_inv_we0;
    sc_out< sc_lv<32> > U_inv_d0;
    sc_in< sc_lv<32> > U_inv_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    Upper_inv(sc_module_name name);
    SC_HAS_PROCESS(Upper_inv);

    ~Upper_inv();

    sc_trace_file* mVcdFile;

    inverse_top_fadd_hbi<1,5,32,32,32>* inverse_top_fadd_hbi_U25;
    inverse_top_fmul_cud<1,4,32,32,32>* inverse_top_fmul_cud_U26;
    inverse_top_fdiv_dEe<1,16,32,32,32>* inverse_top_fdiv_dEe_U27;
    sc_signal< sc_lv<48> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_logic > ap_CS_fsm_state33;
    sc_signal< sc_lv<2> > i_4_fu_228_p2;
    sc_signal< sc_lv<2> > i_4_reg_459;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<5> > sub_ln178_fu_250_p2;
    sc_signal< sc_lv<5> > sub_ln178_reg_464;
    sc_signal< sc_lv<1> > icmp_ln174_fu_222_p2;
    sc_signal< sc_lv<2> > j_fu_262_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<2> > i_fu_288_p2;
    sc_signal< sc_lv<2> > i_reg_480;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<64> > zext_ln184_fu_302_p1;
    sc_signal< sc_lv<64> > zext_ln184_reg_485;
    sc_signal< sc_lv<1> > icmp_ln182_fu_282_p2;
    sc_signal< sc_lv<32> > zext_ln187_fu_307_p1;
    sc_signal< sc_lv<32> > zext_ln187_reg_495;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_lv<2> > i_5_fu_317_p2;
    sc_signal< sc_lv<2> > i_5_reg_503;
    sc_signal< sc_lv<5> > zext_ln198_1_fu_323_p1;
    sc_signal< sc_lv<5> > zext_ln198_1_reg_508;
    sc_signal< sc_lv<1> > icmp_ln187_fu_311_p2;
    sc_signal< sc_lv<4> > U_addr_1_reg_514;
    sc_signal< sc_lv<32> > zext_ln189_fu_340_p1;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<2> > j_5_fu_350_p2;
    sc_signal< sc_lv<2> > j_5_reg_527;
    sc_signal< sc_lv<5> > sub_ln196_fu_372_p2;
    sc_signal< sc_lv<5> > sub_ln196_reg_532;
    sc_signal< sc_lv<1> > icmp_ln189_fu_344_p2;
    sc_signal< sc_lv<4> > U_inv_addr_3_reg_537;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<1> > icmp_ln193_fu_388_p2;
    sc_signal< sc_lv<32> > k_4_fu_435_p2;
    sc_signal< sc_lv<32> > k_4_reg_555;
    sc_signal< sc_lv<32> > grp_fu_203_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_565;
    sc_signal< sc_logic > ap_CS_fsm_state27;
    sc_signal< sc_lv<32> > grp_fu_198_p2;
    sc_signal< sc_logic > ap_CS_fsm_state32;
    sc_signal< sc_lv<32> > bitcast_ln198_1_fu_451_p1;
    sc_signal< sc_lv<2> > i_0_reg_121;
    sc_signal< sc_lv<1> > icmp_ln176_fu_256_p2;
    sc_signal< sc_lv<2> > j_0_reg_132;
    sc_signal< sc_lv<2> > i1_0_reg_143;
    sc_signal< sc_logic > ap_CS_fsm_state20;
    sc_signal< sc_lv<2> > indvars_iv_reg_154;
    sc_signal< sc_lv<2> > k_reg_166;
    sc_signal< sc_logic > ap_CS_fsm_state48;
    sc_signal< sc_lv<32> > sum_0_reg_177;
    sc_signal< sc_lv<32> > k_0_reg_189;
    sc_signal< sc_lv<64> > sext_ln178_fu_277_p1;
    sc_signal< sc_lv<64> > zext_ln198_fu_335_p1;
    sc_signal< sc_lv<64> > sext_ln198_fu_383_p1;
    sc_signal< sc_lv<64> > sext_ln196_fu_420_p1;
    sc_signal< sc_lv<64> > sext_ln196_1_fu_430_p1;
    sc_signal< sc_lv<32> > grp_fu_209_p2;
    sc_signal< sc_logic > ap_CS_fsm_state28;
    sc_signal< sc_lv<32> > grp_fu_209_p0;
    sc_signal< sc_lv<4> > tmp_33_fu_238_p3;
    sc_signal< sc_lv<5> > zext_ln178_1_fu_246_p1;
    sc_signal< sc_lv<5> > zext_ln178_fu_234_p1;
    sc_signal< sc_lv<5> > zext_ln178_2_fu_268_p1;
    sc_signal< sc_lv<5> > add_ln178_fu_272_p2;
    sc_signal< sc_lv<4> > tmp_34_fu_294_p3;
    sc_signal< sc_lv<4> > tmp_35_fu_327_p3;
    sc_signal< sc_lv<4> > tmp_36_fu_360_p3;
    sc_signal< sc_lv<5> > zext_ln196_1_fu_368_p1;
    sc_signal< sc_lv<5> > zext_ln196_fu_356_p1;
    sc_signal< sc_lv<5> > add_ln198_fu_378_p2;
    sc_signal< sc_lv<3> > trunc_ln196_1_fu_397_p1;
    sc_signal< sc_lv<5> > sext_ln196_1_cast_fu_401_p3;
    sc_signal< sc_lv<5> > trunc_ln196_fu_393_p1;
    sc_signal< sc_lv<5> > sub_ln196_1_fu_409_p2;
    sc_signal< sc_lv<5> > add_ln196_fu_415_p2;
    sc_signal< sc_lv<5> > add_ln196_1_fu_425_p2;
    sc_signal< sc_lv<32> > bitcast_ln198_fu_441_p1;
    sc_signal< sc_lv<32> > xor_ln198_fu_445_p2;
    sc_signal< sc_lv<48> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<48> ap_ST_fsm_state1;
    static const sc_lv<48> ap_ST_fsm_state2;
    static const sc_lv<48> ap_ST_fsm_state3;
    static const sc_lv<48> ap_ST_fsm_state4;
    static const sc_lv<48> ap_ST_fsm_state5;
    static const sc_lv<48> ap_ST_fsm_state6;
    static const sc_lv<48> ap_ST_fsm_state7;
    static const sc_lv<48> ap_ST_fsm_state8;
    static const sc_lv<48> ap_ST_fsm_state9;
    static const sc_lv<48> ap_ST_fsm_state10;
    static const sc_lv<48> ap_ST_fsm_state11;
    static const sc_lv<48> ap_ST_fsm_state12;
    static const sc_lv<48> ap_ST_fsm_state13;
    static const sc_lv<48> ap_ST_fsm_state14;
    static const sc_lv<48> ap_ST_fsm_state15;
    static const sc_lv<48> ap_ST_fsm_state16;
    static const sc_lv<48> ap_ST_fsm_state17;
    static const sc_lv<48> ap_ST_fsm_state18;
    static const sc_lv<48> ap_ST_fsm_state19;
    static const sc_lv<48> ap_ST_fsm_state20;
    static const sc_lv<48> ap_ST_fsm_state21;
    static const sc_lv<48> ap_ST_fsm_state22;
    static const sc_lv<48> ap_ST_fsm_state23;
    static const sc_lv<48> ap_ST_fsm_state24;
    static const sc_lv<48> ap_ST_fsm_state25;
    static const sc_lv<48> ap_ST_fsm_state26;
    static const sc_lv<48> ap_ST_fsm_state27;
    static const sc_lv<48> ap_ST_fsm_state28;
    static const sc_lv<48> ap_ST_fsm_state29;
    static const sc_lv<48> ap_ST_fsm_state30;
    static const sc_lv<48> ap_ST_fsm_state31;
    static const sc_lv<48> ap_ST_fsm_state32;
    static const sc_lv<48> ap_ST_fsm_state33;
    static const sc_lv<48> ap_ST_fsm_state34;
    static const sc_lv<48> ap_ST_fsm_state35;
    static const sc_lv<48> ap_ST_fsm_state36;
    static const sc_lv<48> ap_ST_fsm_state37;
    static const sc_lv<48> ap_ST_fsm_state38;
    static const sc_lv<48> ap_ST_fsm_state39;
    static const sc_lv<48> ap_ST_fsm_state40;
    static const sc_lv<48> ap_ST_fsm_state41;
    static const sc_lv<48> ap_ST_fsm_state42;
    static const sc_lv<48> ap_ST_fsm_state43;
    static const sc_lv<48> ap_ST_fsm_state44;
    static const sc_lv<48> ap_ST_fsm_state45;
    static const sc_lv<48> ap_ST_fsm_state46;
    static const sc_lv<48> ap_ST_fsm_state47;
    static const sc_lv<48> ap_ST_fsm_state48;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_3F800000;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_80000000;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_U_address0();
    void thread_U_ce0();
    void thread_U_inv_address0();
    void thread_U_inv_ce0();
    void thread_U_inv_d0();
    void thread_U_inv_we0();
    void thread_add_ln178_fu_272_p2();
    void thread_add_ln196_1_fu_425_p2();
    void thread_add_ln196_fu_415_p2();
    void thread_add_ln198_fu_378_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state20();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state27();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state32();
    void thread_ap_CS_fsm_state33();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state48();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_bitcast_ln198_1_fu_451_p1();
    void thread_bitcast_ln198_fu_441_p1();
    void thread_grp_fu_209_p0();
    void thread_i_4_fu_228_p2();
    void thread_i_5_fu_317_p2();
    void thread_i_fu_288_p2();
    void thread_icmp_ln174_fu_222_p2();
    void thread_icmp_ln176_fu_256_p2();
    void thread_icmp_ln182_fu_282_p2();
    void thread_icmp_ln187_fu_311_p2();
    void thread_icmp_ln189_fu_344_p2();
    void thread_icmp_ln193_fu_388_p2();
    void thread_j_5_fu_350_p2();
    void thread_j_fu_262_p2();
    void thread_k_4_fu_435_p2();
    void thread_sext_ln178_fu_277_p1();
    void thread_sext_ln196_1_cast_fu_401_p3();
    void thread_sext_ln196_1_fu_430_p1();
    void thread_sext_ln196_fu_420_p1();
    void thread_sext_ln198_fu_383_p1();
    void thread_sub_ln178_fu_250_p2();
    void thread_sub_ln196_1_fu_409_p2();
    void thread_sub_ln196_fu_372_p2();
    void thread_tmp_33_fu_238_p3();
    void thread_tmp_34_fu_294_p3();
    void thread_tmp_35_fu_327_p3();
    void thread_tmp_36_fu_360_p3();
    void thread_trunc_ln196_1_fu_397_p1();
    void thread_trunc_ln196_fu_393_p1();
    void thread_xor_ln198_fu_445_p2();
    void thread_zext_ln178_1_fu_246_p1();
    void thread_zext_ln178_2_fu_268_p1();
    void thread_zext_ln178_fu_234_p1();
    void thread_zext_ln184_fu_302_p1();
    void thread_zext_ln187_fu_307_p1();
    void thread_zext_ln189_fu_340_p1();
    void thread_zext_ln196_1_fu_368_p1();
    void thread_zext_ln196_fu_356_p1();
    void thread_zext_ln198_1_fu_323_p1();
    void thread_zext_ln198_fu_335_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
